### ISSUE TITLE
Start the training by running: python train.py

### ISSUE THREAD

**Issue by YX123YX** [AaronCCWong/Show-Attend-and-Tell#2]
Start the training by running: python train.py

Traceback (most recent call last):
  File "C:/‘’‘’‘’/show-attend-and-tell-master/train.py", line 201, in <module>
    main(parser.parse_args())
  File "C:/‘’‘’‘’‘’/show-attend-and-tell-master/train.py", line 32, in main
    decoder = Decoder(vocabulary_size, encoder.dim, args.tf)
  File "C:\’‘’‘’\show-attend-and-tell-master\decoder.py", line 24, in __init__
    self.attention = Attention(encoder_dim)
  File "C:\‘’‘’‘’\show-attend-and-tell-master\attention.py", line 12, in __init__
    self.softmax = nn.Softmax(1)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by AaronCCWong** [comment]
Thanks for pointing this out. What version of pytorch are you using?

**Comment by YX123YX** [comment]
> 感谢您指出了这一点。你用的是什么版本的pytorch？

>>> print(torch.__version__)
0.1.12
I am just starting to learn. My topic is to study this. I hope to implement it first and then improve it.

**Comment by AaronCCWong** [comment]
Ah I see. If you upgrade to `0.4.1` or `1.0.0` then it should work. 

The version you are using was released over a year and a half ago so it might make sense to use a more up to date version to learn. Do let me know if there is something in this repo you don't understand. I will try my best to help you.

**Comment by YX123YX** [comment]
> Ah I see. If you upgrade to `0.4.1` or `1.0.0` then it should work.
> 
> The version you are using was released over a year and a half ago so it might make sense to use a more up to date version to learn. Do let me know if there is something in this repo you don't understand. I will try my best to help you.

I will try it, thank you very much.
