### ISSUE TITLE
blue results are different

### ISSUE THREAD

**Issue by YX123YX** [AaronCCWong/Show-Attend-and-Tell#4]
The result of my training according to the program is:

> Validation Epoch: 10 BLEU-1 (0.5654905751570807) BLEU-2 (0.3145844613210465) BLEU-3 (0.17715332243387322) BLEU-4 (0.09759658219013374)
Saved model to model/model_vgg19_10.pth

Not the same as what you provided。

**Comment by AaronCCWong** [comment]
It should print the args that you are training with when training starts. Can you copy and paste that here?

**Comment by YX123YX** [comment]
> 它应该在训练开始时打印你正在训练的参数。你能在这里复制粘贴吗？

Starting training with Namespace(alpha_c=1, batch_size=64, data='data/coco', epochs=10, log_interval=100, lr=0.0001, model=None, network='vgg19', step_size=5, tf=False)
...
Validation Epoch: 1	BLEU-1 (0.526093684062456)	BLEU-2 (0.26891523608051665)	BLEU-3 (0.13817096267878967)	BLEU-4 (0.06909855289300085)	
Saved model to model/model_vgg19_1.pth
...
Validation Epoch: 2	BLEU-1 (0.5415606638415027)	BLEU-2 (0.2857463429766803)	BLEU-3 (0.15541844385669729)	BLEU-4 (0.08112380915009178)	
Saved model to model/model_vgg19_2.pth
...
...
...
Validation Epoch: 10 BLEU-1 (0.5654905751570807)	BLEU-2 (0.3145844613210465)	BLEU-3 (0.17715332243387322)	BLEU-4 (0.09759658219013374)	
Saved model to model/model_vgg19_10.pth

**Comment by YX123YX** [comment]
> It should print the args that you are training with when training starts. Can you copy and paste that here?

Starting training with Namespace(alpha_c=1, batch_size=64, data='data/coco', epochs=10, log_interval=100, lr=0.0001, model=None, network='vgg19', step_size=5, tf=False)
...
Validation Epoch: 1	BLEU-1 (0.526093684062456)	BLEU-2 (0.26891523608051665)	BLEU-3 (0.13817096267878967)	BLEU-4 (0.06909855289300085)	
Saved model to model/model_vgg19_1.pth
...
Validation Epoch: 2	BLEU-1 (0.5415606638415027)	BLEU-2 (0.2857463429766803)	BLEU-3 (0.15541844385669729)	BLEU-4 (0.08112380915009178)	
Saved model to model/model_vgg19_2.pth
...
...
...
Validation Epoch: 10 BLEU-1 (0.5654905751570807)	BLEU-2 (0.3145844613210465)	BLEU-3 (0.17715332243387322)	BLEU-4 (0.09759658219013374)	
Saved model to model/model_vgg19_10.pth

**Comment by AaronCCWong** [comment]
Training with `tf=True` should give you the results you are looking for.

**Comment by YX123YX** [comment]
> Training with `tf=True` should give you the results you are looking for.

Just starting to learn, maybe some simple questions will ask you, I am very sorry about this.
