### ISSUE TITLE
BLEU-4 does not move above 0.10 for ten epochs

### ISSUE THREAD

**Issue by morawi** [AaronCCWong/Show-Attend-and-Tell#7]
Thank you so much for sharing this wonderful code, and it is working immediately out of the box. 
I just have a simple question;  the BLUE scores do not get to the ones shown in your graphs.
For example, BLUE-4 does not go above 0.10 after ten epochs, while in your graphs it reaches a value around 0.27. 
Have you done the experiments differently, using some training protocol or another initialization?

Thanks again

**Comment by TodayUp** [comment]
> Thank you so much for sharing this wonderful code, and it is working immediately out of the box.
> I just have a simple question, as the BLUE scored do not get to the ones shown in your graphs.
> For example, BLUE-4 does not go above 0.10 after ten epochs, while in your graphs it reaches a value around 0.27.
> Have you done the experiments differently, using some training protocol or another initialization?
> 
> Thanks again

I got the same problem.

**Comment by AaronCCWong** [comment]
I will take a look in the coming few days. I apologize for the delay.

**Comment by morawi** [comment]
@AaronCCWong @TodayUp 
It worked, I have to change `store_true` to `True`

```
 parser.add_argument('--tf', action='store_true', default=True,
                        help='Use teacher forcing when training LSTM (default: False)')
```
and I got 
```
Validation Epoch: 10    BLEU-1 (0.7176654391250976)     BLEU-2 (0.5160380704764339)     BLEU-3 (0.3693062083947734)     BLEU-4 (0.25955264539591494)    
Saved model to model/model_vgg19_10.pth
```

**Comment by AaronCCWong** [comment]
@morawi Ah yes, thanks for pointing that out. This is because `--tf` enables teacher forcing while training allowing it to train much faster. I will need to update the README to make this clearer.

Feel free to reopen this issue if the problem still occurs for you @TodayUp
